const fs = require('fs');

const games = [
 { url: 'https://mathv2.b-cdn.net/study2/691.html', title: 'Heartbreak Havoc' },
 { url: 'https://mathv2.b-cdn.net/study2/477.html', title: 'Friday Night Funkin\' + Hatsune Miku' },
 { url: 'https://mathv2.b-cdn.net/study2/476.html', title: 'Friday Night Funkin\' (Alternative)' },
 { url: 'https://mathv2.b-cdn.net/study2/474.html', title: 'Friday Night Funkin\'' },
 { url: 'https://mathv2.b-cdn.net/study/adofai/index.html', title: 'A Dance of Fire and Ice' },
 { url: 'https://mathv2.b-cdn.net/study/thisistheonlylevel/index.html', title: 'This Is The Only Level' },
 { url: 'https://mathv2.b-cdn.net/study/superstarsaga/index.html', title: 'Mario & Luigi Superstar Saga' },
 { url: 'https://mathv2.b-cdn.net/study/pokemonsapphire/index.html', title: 'Pokemon Sapphire' },
 { url: 'https://mathv2.b-cdn.net/study/pokemonruby/index.html', title: 'Pokemon Ruby' },
 { url: 'https://mathv2.b-cdn.net/study/pokemonleafgreen/index.html', title: 'Pokemon LeafGreen' },
 { url: 'https://mathv2.b-cdn.net/study/mariokartsupercircuit/index.html', title: 'Mario Kart Super Circuit' },
 { url: 'https://mathv2.b-cdn.net/study/iceclimber/index.html', title: 'Ice Climber' },
 { url: 'https://mathv2.b-cdn.net/study/bomberman/index.html', title: 'Bomberman' },
 { url: 'https://mathv2.b-cdn.net/study/fireemblem/index.html', title: 'Fire Emblem' },
 { url: 'https://mathv2.b-cdn.net/study/btd/btd4/index.html', title: 'Bloons TD 4' },
 { url: 'https://mathv2.b-cdn.net/study/btd/btd3/index.html', title: 'Bloons TD 3' },
 { url: 'https://mathv2.b-cdn.net/study/btd/btd/index.html', title: 'Bloons TD' },
 { url: 'https://mathv2.b-cdn.net/study/btd/btd2/index.html', title: 'Bloons TD 2' },
 { url: 'https://mathv2.b-cdn.net/study/colorswitch/index.html', title: 'Color Switch' },
 { url: 'https://mathv2.b-cdn.net/study/papasfreezeria/index.html', title: 'Papa\'s Freezeria' },
 { url: 'https://mathv2.b-cdn.net/study/supermarioland/index.html', title: 'Super Mario Land' },
 { url: 'https://mathv2.b-cdn.net/study/dogeminer/index.html', title: 'Doge Miner' },
 { url: 'https://mathv2.b-cdn.net/study/donkeykongland/index.html', title: 'Donkey Kong Land' },
 { url: 'https://mathv2.b-cdn.net/study/kirbysdreamland/index.html', title: 'Kirby\'s Dreamland' },
 { url: 'https://mathv2.b-cdn.net/study/warioware/index.html', title: 'WarioWare' },
 { url: 'https://mathv2.b-cdn.net/study/yoshisisland/index.html', title: 'Yoshi\'s Island' },
 { url: 'https://mathv2.b-cdn.net/study/supermariobros3/index.html', title: 'Super Mario Bros 3' },
 { url: 'https://mathv2.b-cdn.net/study/thelegendofzelda/index.html', title: 'The Legend of Zelda' },
 { url: 'https://mathv2.b-cdn.net/study/metroid/index.html', title: 'Metroid' },
 { url: 'https://mathv2.b-cdn.net/study/supermariobros2/index.html', title: 'Super Mario Bros 2' },
 { url: 'https://mathv2.b-cdn.net/study/donkeykong/index.html', title: 'Donkey Kong' },
 { url: 'https://mathv2.b-cdn.net/study/drmario/index.html', title: 'Dr. Mario' },
 { url: 'https://mathv2.b-cdn.net/study/worldshardestgame/index.html', title: 'World\'s Hardest Game' },
 { url: 'https://mathv2.b-cdn.net/study/castlevania/index.html', title: 'Castlevania' },
 { url: 'https://mathv2.b-cdn.net/study/supermarioworld/index.html', title: 'Super Mario World' },
 { url: 'https://mathv2.b-cdn.net/study/thereisnogame/index.html', title: 'There Is No Game' },
 { url: 'https://mathv2.b-cdn.net/study/supermariobros/index.html', title: 'Super Mario Bros' },
 { url: 'https://mathv2.b-cdn.net/study/pokemonfirered/index.html', title: 'Pokemon FireRed' },
 { url: 'https://mathv2.b-cdn.net/study/pokemonemerald/index.html', title: 'Pokemon Emerald' },
 { url: 'https://mathv2.b-cdn.net/study/minesweeper/index.html', title: 'Minesweeper' },
 { url: 'https://mathv2.b-cdn.net/study/bobtherobber2/index.html', title: 'Bob The Robber 2' },
 { url: 'https://mathv2.b-cdn.net/study/papaspancakeria/index.html', title: 'Papa\'s Pancakeria' },
 { url: 'https://mathv2.b-cdn.net/study/pacman/index.html', title: 'Pac-Man' },
 { url: 'https://mathv2.b-cdn.net/study/fnf/index.html', title: 'Friday Night Funkin\'' },
 { url: 'https://mathv2.b-cdn.net/study/driftboss/index.html', title: 'Drift Boss' },
 { url: 'https://mathv2.b-cdn.net/study/riddleschool/riddletransfer2/index.html', title: 'Riddle Transfer 2' },
 { url: 'https://mathv2.b-cdn.net/study/riddleschool/riddletransfer/index.html', title: 'Riddle Transfer' },
 { url: 'https://mathv2.b-cdn.net/study/riddleschool/riddleschool5/index.html', title: 'Riddle School 5' },
 { url: 'https://mathv2.b-cdn.net/study/riddleschool/riddleschool4/index.html', title: 'Riddle School 4' },
 { url: 'https://mathv2.b-cdn.net/study/riddleschool/riddleschool3/index.html', title: 'Riddle School 3' },
 { url: 'https://mathv2.b-cdn.net/study/riddleschool/riddleschool2/index.html', title: 'Riddle School 2' },
 { url: 'https://mathv2.b-cdn.net/study/riddleschool/riddleschool1/index.html', title: 'Riddle School 1' },
 { url: 'https://mathv2.b-cdn.net/study/fnaf-4/index.html', title: 'Five Nights at Freddy\'s 4' },
 { url: 'https://mathv2.b-cdn.net/study/fnaf-3/index.html', title: 'Five Nights at Freddy\'s 3' },
 { url: 'https://mathv2.b-cdn.net/study/fnaf-2/index.html', title: 'Five Nights at Freddy\'s 2' },
 { url: 'https://mathv2.b-cdn.net/study/fnaf/index.html', title: 'Five Nights at Freddy\'s' },
 { url: 'https://mathv2.b-cdn.net/study/roblox.html', title: 'Roblox' },
 { url: 'https://mathv2.b-cdn.net/study/motox3m/index.html', title: 'Moto X3M' },
 { url: 'https://mathv2.b-cdn.net/study/surf/index.html', title: 'Surf' },
 { url: 'https://mathv2.b-cdn.net/study/vex6/index.html', title: 'Vex 6' },
 { url: 'https://mathv2.b-cdn.net/study/webecomewhatwebehold/index.html', title: 'We Become What We Behold' },
 { url: 'https://mathv2.b-cdn.net/study/theimpossiblequiz/index.html', title: 'The Impossible Quiz' },
 { url: 'https://mathv2.b-cdn.net/study/solitaire/index.html', title: 'Solitaire' },
 { url: 'https://mathv2.b-cdn.net/study/escapingtheprison/index.html', title: 'Escaping the Prison' },
 { url: 'https://mathv2.b-cdn.net/study/stealingthediamond/index.html', title: 'Stealing the Diamond' },
 { url: 'https://mathv2.b-cdn.net/study/tunnelrush/index.html', title: 'Tunnel Rush' },
 { url: 'https://mathv2.b-cdn.net/study/themehotel/index.html', title: 'Theme Hotel' },
 { url: 'https://mathv2.b-cdn.net/study/happywheels/index.html', title: 'Happy Wheels' },
 { url: 'https://mathv2.b-cdn.net/study/papashotdoggeria/index.html', title: 'Papa\'s Hot Doggeria' },
 { url: 'https://mathv2.b-cdn.net/study/tetris/index.html', title: 'Tetris' },
 { url: 'https://mathv2.b-cdn.net/study/fancypantsadventure/index.html', title: 'Fancy Pants Adventure' },
 { url: 'https://mathv2.b-cdn.net/study/2048/index.html', title: '2048' },
 { url: 'https://mathv2.b-cdn.net/study/jetpackjoyride/index.html', title: 'Jetpack Joyride' },
 { url: 'https://mathv2.b-cdn.net/study/dinogame/index.html', title: 'Dino Game' },
 { url: 'https://mathv2.b-cdn.net/study/ducklife4/index.html', title: 'Duck Life 4' },
 { url: 'https://mathv2.b-cdn.net/study/templerun2/index.html', title: 'Temple Run 2' },
 { url: 'https://mathv2.b-cdn.net/study/cookieclicker/index.html', title: 'Cookie Clicker' },
 { url: 'https://mathv2.b-cdn.net/study/mc/index.html', title: 'Minecraft' },
 { url: 'https://mathv2.b-cdn.net/study/crossy/index.html', title: 'Crossy Road' },
 { url: 'https://mathv2.b-cdn.net/study/bitlife/index.html', title: 'BitLife' },
 { url: 'https://mathv2.b-cdn.net/study/zrist/index.html', title: 'Zrist' },
 { url: 'https://mathv2.b-cdn.net/study/run3/index.html', title: 'Run 3' },
 { url: 'https://mathv2.b-cdn.net/study/repo/index.html', title: 'Repo' },
 { url: 'https://mathv2.b-cdn.net/study/thatsnotmyneighbor/index.html', title: 'That\'s Not My Neighbor' },
 { url: 'https://mathv2.b-cdn.net/study/velocity-rush/index.html', title: 'Velocity Rush' },
 { url: 'https://mathv2.b-cdn.net/study/omori/index.html', title: 'Omori' },
 { url: 'https://mathv2.b-cdn.net/study/sm64/index.html', title: 'Super Mario 64' },
 { url: 'https://mathv2.b-cdn.net/study/papaspizzaria/index.html', title: 'Papa\'s Pizzeria' },
 { url: 'https://mathv2.b-cdn.net/study/papasburgeria/index.html', title: 'Papa\'s Burgeria' },
 { url: 'https://mathv2.b-cdn.net/study/slope/index.html', title: 'Slope' },
 { url: 'https://mathv2.b-cdn.net/study/subwaysurfers/index.html', title: 'Subway Surfers' }
];

const mappedGames = games.map((g, index) => ({
  id: String(index + 1),
  title: g.title,
  description: `Play ${g.title} on AlphaOS`,
  url: g.url,
  image: `https://ui-avatars.com/api/?name=${encodeURIComponent(g.title)}&background=random&color=fff&size=256`
}));

fs.writeFileSync('./public/voltzbot.json', JSON.stringify(mappedGames, null, 2));
